# Generated by Django 4.2.4 on 2023-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ful_name', models.CharField(max_length=50)),
                ('Employee_id', models.IntegerField(max_length=15)),
                ('interview_start_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interview_end_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hr_number', models.IntegerField(max_length=15)),
                ('hr_mail_id', models.EmailField(max_length=254)),
                ('hr_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('interview_round', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('ToDo', 'ToDo'), ('Rescheduled', 'Rescheduled')], max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('Python', 'Python'), ('Data Engineering', 'Data Engineering')], max_length=20)),
            ],
        ),
    ]
